#!/bin/sh
cd /tmp/work
magiskboot cpio ramdisk.cpio \
"add 750 twres/images/fileTheme.png /twres/images/fileTheme.png" \
"add 750 twres/images/fileImg.png /twres/images/fileImg.png" \
"add 750 twres/images/c_dashboard_reboot.png /twres/images/c_dashboard_reboot.png" \
"add 750 twres/images/moreCustomization.png /twres/images/moreCustomization.png" \
"add 750 twres/images/slotPanel.png /twres/images/slotPanel.png" \
"add 750 twres/images/c_battery_20.png /twres/images/c_battery_20.png" \
"add 750 twres/images/showComponent.png /twres/images/showComponent.png" \
"add 750 twres/images/kb_show.png /twres/images/kb_show.png" \
"add 750 twres/images/c_adb.png /twres/images/c_adb.png" \
"add 750 twres/images/actionFolderInfo.png /twres/images/actionFolderInfo.png" \
"add 750 twres/images/shift_fill.png /twres/images/shift_fill.png" \
"add 750 twres/images/officialBuild.png /twres/images/officialBuild.png" \
"add 750 twres/images/hideComponent.png /twres/images/hideComponent.png" \
"add 750 twres/images/folder.png /twres/images/folder.png" \
"add 750 twres/images/c_download_mode.png /twres/images/c_download_mode.png" \
"add 750 twres/images/shrpSettings.png /twres/images/shrpSettings.png" \
"add 750 twres/images/actionWipe.png /twres/images/actionWipe.png" \
"add 750 twres/images/c_power_menu_bg.png /twres/images/c_power_menu_bg.png" \
"add 750 twres/images/c_dashboard_flash.png /twres/images/c_dashboard_flash.png" \
"add 750 twres/images/actionPaste.png /twres/images/actionPaste.png" \
"add 750 twres/images/c_dashboard_mount.png /twres/images/c_dashboard_mount.png" \
"add 750 twres/images/back.png /twres/images/back.png" \
"add 750 twres/images/c_battery_90.png /twres/images/c_battery_90.png" \
"add 750 twres/images/c_usersRadioOff.png /twres/images/c_usersRadioOff.png" \
"add 750 twres/images/editFile.png /twres/images/editFile.png" \
"add 750 twres/images/c_usersRadioOn.png /twres/images/c_usersRadioOn.png" \
"add 750 twres/images/c_dashboard_backup.png /twres/images/c_dashboard_backup.png" \
"add 750 twres/images/actionZipOperation.png /twres/images/actionZipOperation.png" \
"add 750 twres/images/c_rounded_3.png /twres/images/c_rounded_3.png" \
"add 750 twres/images/folderUp.png /twres/images/folderUp.png" \
"add 750 twres/images/c_dashboard_wipe.png /twres/images/c_dashboard_wipe.png" \
"add 750 twres/images/c_reload.png /twres/images/c_reload.png" \
"add 750 twres/images/actionArchive.png /twres/images/actionArchive.png" \
"add 750 twres/images/c_power_off.png /twres/images/c_power_off.png" \
"add 750 twres/images/actionApplyTheme.png /twres/images/actionApplyTheme.png" \
"add 750 twres/images/globeIco.png /twres/images/globeIco.png" \
"add 750 twres/images/magiskModule.png /twres/images/magiskModule.png" \
"add 750 twres/images/generalSettingsDisabled.png /twres/images/generalSettingsDisabled.png" \
"add 750 twres/images/permButton.png /twres/images/permButton.png" \
"add 750 twres/images/fileMangerSettings.png /twres/images/fileMangerSettings.png" \
"add 750 twres/images/c_reboot_to_system.png /twres/images/c_reboot_to_system.png" \
"add 750 twres/images/controlLock.png /twres/images/controlLock.png" \
"add 750 twres/images/actionRebootRecovery.png /twres/images/actionRebootRecovery.png" \
"add 750 twres/images/deviceIco.png /twres/images/deviceIco.png" \
"add 750 twres/images/fileImg2.png /twres/images/fileImg2.png" \
"add 750 twres/images/folderUnselected.png /twres/images/folderUnselected.png" \
"add 750 twres/images/c_epicxsort.png /twres/images/c_epicxsort.png" \
"add 750 twres/images/c_mod.png /twres/images/c_mod.png" \
"add 750 twres/images/kb_arrow_left.png /twres/images/kb_arrow_left.png" \
"add 750 twres/images/actionRebootSystem.png /twres/images/actionRebootSystem.png" \
"add 750 twres/images/c_edl_mode.png /twres/images/c_edl_mode.png" \
"add 750 twres/images/deviceSettingsDisabled.png /twres/images/deviceSettingsDisabled.png" \
"add 750 twres/images/generalSettings.png /twres/images/generalSettings.png" \
"add 750 twres/images/fileLocExternal.png /twres/images/fileLocExternal.png" \
"add 750 twres/images/dashboardBackground.png /twres/images/dashboardBackground.png" \
"add 750 twres/images/kb_arrow_right.png /twres/images/kb_arrow_right.png" \
"add 750 twres/images/folderSelected.png /twres/images/folderSelected.png" \
"add 750 twres/images/enter.png /twres/images/enter.png" \
"add 750 twres/images/shrpSettingsDisabled.png /twres/images/shrpSettingsDisabled.png" \
"add 750 twres/images/file.png /twres/images/file.png" \
"add 750 twres/images/fileLocInternal.png /twres/images/fileLocInternal.png" \
"add 750 twres/images/controlFlashOn.png /twres/images/controlFlashOn.png" \
"add 750 twres/images/c_rounded_2.png /twres/images/c_rounded_2.png" \
"add 750 twres/images/toggleOff.png /twres/images/toggleOff.png" \
"add 750 twres/images/search.png /twres/images/search.png" \
"add 750 twres/images/openSideBar.png /twres/images/openSideBar.png" \
"add 750 twres/images/c_battery_low.png /twres/images/c_battery_low.png" \
"add 750 twres/images/c_sd_part.png /twres/images/c_sd_part.png" \
"add 750 twres/images/actionRename.png /twres/images/actionRename.png" \
"add 750 twres/images/installSign.png /twres/images/installSign.png" \
"add 750 twres/images/c_rounded_1.png /twres/images/c_rounded_1.png" \
"add 750 twres/images/actionOption.png /twres/images/actionOption.png" \
"add 750 twres/images/c_dashboard_magisk.png /twres/images/c_dashboard_magisk.png" \
"add 750 twres/images/checkbox_true.png /twres/images/checkbox_true.png" \
"add 750 twres/images/dashboardList.png /twres/images/dashboardList.png" \
"add 750 twres/images/editPermissions.png /twres/images/editPermissions.png" \
"add 750 twres/images/c_dashboard_filemanager.png /twres/images/c_dashboard_filemanager.png" \
"add 750 twres/images/actionCut.png /twres/images/actionCut.png" \
"add 750 twres/images/kb_arrow_up.png /twres/images/kb_arrow_up.png" \
"add 750 twres/images/c_selinux.png /twres/images/c_selinux.png" \
"add 750 twres/images/batteryList.png /twres/images/batteryList.png" \
"add 750 twres/images/fileLocRoot.png /twres/images/fileLocRoot.png" \
"add 750 twres/images/actionCreateFolder.png /twres/images/actionCreateFolder.png" \
"add 750 twres/images/c_battery_50.png /twres/images/c_battery_50.png" \
"add 750 twres/images/c_dashboard_restore.png /twres/images/c_dashboard_restore.png" \
"add 750 twres/images/deviceSettings.png /twres/images/deviceSettings.png" \
"add 750 twres/images/actionCopyLog.png /twres/images/actionCopyLog.png" \
"add 750 twres/images/home.png /twres/images/home.png" \
"add 750 twres/images/actionSelectMultipleFile.png /twres/images/actionSelectMultipleFile.png" \
"add 750 twres/images/c_dashboard_terminal.png /twres/images/c_dashboard_terminal.png" \
"add 750 twres/images/c_reboot_to_bootloader.png /twres/images/c_reboot_to_bootloader.png" \
"add 750 twres/images/backspace.png /twres/images/backspace.png" \
"add 750 twres/images/shift.png /twres/images/shift.png" \
"add 750 twres/images/shrpCredits.png /twres/images/shrpCredits.png" \
"add 750 twres/images/c_dashboard_lock.png /twres/images/c_dashboard_lock.png" \
"add 750 twres/images/betaBuild.png /twres/images/betaBuild.png" \
"add 750 twres/images/c_dashboard_about.png /twres/images/c_dashboard_about.png" \
"add 750 twres/images/space.png /twres/images/space.png" \
"add 750 twres/images/c_battery_60.png /twres/images/c_battery_60.png" \
"add 750 twres/images/toggleOn.png /twres/images/toggleOn.png" \
"add 750 twres/images/fileSelected.png /twres/images/fileSelected.png" \
"add 750 twres/images/timeSettings.png /twres/images/timeSettings.png" \
"add 750 twres/images/actionUnselectMultipleFile.png /twres/images/actionUnselectMultipleFile.png" \
"add 750 twres/images/fileArchive.png /twres/images/fileArchive.png" \
"add 750 twres/images/actionDelete.png /twres/images/actionDelete.png" \
"add 750 twres/images/c_splash_bg.png /twres/images/c_splash_bg.png" \
"add 750 twres/images/fileLocOtg.png /twres/images/fileLocOtg.png" \
"add 750 twres/images/c_dashboard_addon.png /twres/images/c_dashboard_addon.png" \
"add 750 twres/images/fileLocSystem.png /twres/images/fileLocSystem.png" \
"add 750 twres/images/actionCopy.png /twres/images/actionCopy.png" \
"add 750 twres/images/c_battery_30.png /twres/images/c_battery_30.png" \
"add 750 twres/images/backup.png /twres/images/backup.png" \
"add 750 twres/images/timeSettingsDisabled.png /twres/images/timeSettingsDisabled.png" \
"add 750 twres/images/c_dateSort.png /twres/images/c_dateSort.png" \
"add 750 twres/images/handle.png /twres/images/handle.png" \
"add 750 twres/images/goodSign.png /twres/images/goodSign.png" \
"add 750 twres/images/c_log.png /twres/images/c_log.png" \
"add 750 twres/images/colorEnabled.png /twres/images/colorEnabled.png" \
"add 750 twres/images/c_battery_80.png /twres/images/c_battery_80.png" \
"add 750 twres/images/fileUnselected.png /twres/images/fileUnselected.png" \
"add 750 twres/images/sliderDot.png /twres/images/sliderDot.png" \
"add 750 twres/images/c_line.png /twres/images/c_line.png" \
"add 750 twres/images/c_clear_input.png /twres/images/c_clear_input.png" \
"add 750 twres/images/c_circle4.png /twres/images/c_circle4.png" \
"add 750 twres/images/c_dashboard_advanced.png /twres/images/c_dashboard_advanced.png" \
"add 750 twres/images/console.png /twres/images/console.png" \
"add 750 twres/images/radio_false.png /twres/images/radio_false.png" \
"add 750 twres/images/c_reboot_to_recovery.png /twres/images/c_reboot_to_recovery.png" \
"add 750 twres/images/c_advanced.png /twres/images/c_advanced.png" \
"add 750 twres/images/kb_arrow_down.png /twres/images/kb_arrow_down.png" \
"add 750 twres/images/c_ok.png /twres/images/c_ok.png" \
"add 750 twres/images/c_dashboard_settings.png /twres/images/c_dashboard_settings.png" \
"add 750 twres/images/c_rounded_4.png /twres/images/c_rounded_4.png" \
"add 750 twres/images/controlFlashOff.png /twres/images/controlFlashOff.png" \
"add 750 twres/images/radio_true.png /twres/images/radio_true.png" \
"add 750 twres/images/SKYHAWK.png /twres/images/SKYHAWK.png" \
"add 750 twres/images/c_battery_full.png /twres/images/c_battery_full.png" \
"add 750 twres/images/checkbox_false.png /twres/images/checkbox_false.png" \
"add 750 twres/images/c_dashboard_userFbe.png /twres/images/c_dashboard_userFbe.png" \
"add 750 twres/images/c_dashboard_more.png /twres/images/c_dashboard_more.png" \
"add 750 twres/images/c_dashboard_lang.png /twres/images/c_dashboard_lang.png" \
"add 750 twres/dynamic/themeData.xml /twres/dynamic/themeData.xml" \
"add 750 twres/slts /twres/slts"
