#!/bin/sh
cd /tmp/work
/system/bin/magiskboot cpio ramdisk.cpio \
"add 750 twres/images/fileTheme.png /twres/images/fileTheme.png" \
"add 750 twres/images/listcolorDarkGreen.png /twres/images/listcolorDarkGreen.png" \
"add 750 twres/images/fileImg.png /twres/images/fileImg.png" \
"add 750 twres/images/c_battery_bar_015.png /twres/images/c_battery_bar_015.png" \
"add 750 twres/images/c_battery_bar_060.png /twres/images/c_battery_bar_060.png" \
"add 750 twres/images/c_apply_theme.png /twres/images/c_apply_theme.png" \
"add 750 twres/images/c_dashboard_reboot.png /twres/images/c_dashboard_reboot.png" \
"add 750 twres/images/moreCustomization.png /twres/images/moreCustomization.png" \
"add 750 twres/images/slotPanel.png /twres/images/slotPanel.png" \
"add 750 twres/images/c_battery_20.png /twres/images/c_battery_20.png" \
"add 750 twres/images/showComponent.png /twres/images/showComponent.png" \
"add 750 twres/images/colorPink.png /twres/images/colorPink.png" \
"add 750 twres/images/kb_show.png /twres/images/kb_show.png" \
"add 750 twres/images/c_battery_bar_085.png /twres/images/c_battery_bar_085.png" \
"add 750 twres/images/c_adb.png /twres/images/c_adb.png" \
"add 750 twres/images/actionFolderInfo.png /twres/images/actionFolderInfo.png" \
"add 750 twres/images/shift_fill.png /twres/images/shift_fill.png" \
"add 750 twres/images/officialBuild.png /twres/images/officialBuild.png" \
"add 750 twres/images/hideComponent.png /twres/images/hideComponent.png" \
"add 750 twres/images/c_battery_bar_005.png /twres/images/c_battery_bar_005.png" \
"add 750 twres/images/folder.png /twres/images/folder.png" \
"add 750 twres/images/c_shadow_invert.png /twres/images/c_shadow_invert.png" \
"add 750 twres/images/listcolorRandom.png /twres/images/listcolorRandom.png" \
"add 750 twres/images/c_download_mode.png /twres/images/c_download_mode.png" \
"add 750 twres/images/shrpSettings.png /twres/images/shrpSettings.png" \
"add 750 twres/images/actionWipe.png /twres/images/actionWipe.png" \
"add 750 twres/images/colorCyan.png /twres/images/colorCyan.png" \
"add 750 twres/images/c_power_menu_bg.png /twres/images/c_power_menu_bg.png" \
"add 750 twres/images/c_dashboard_flash.png /twres/images/c_dashboard_flash.png" \
"add 750 twres/images/actionPaste.png /twres/images/actionPaste.png" \
"add 750 twres/images/listcolorWhite.png /twres/images/listcolorWhite.png" \
"add 750 twres/images/listcolorLred.png /twres/images/listcolorLred.png" \
"add 750 twres/images/unofficialBuild.png /twres/images/unofficialBuild.png" \
"add 750 twres/images/c_battery_bar_065.png /twres/images/c_battery_bar_065.png" \
"add 750 twres/images/c_dashboard_mount.png /twres/images/c_dashboard_mount.png" \
"add 750 twres/images/listcolorBrown.png /twres/images/listcolorBrown.png" \
"add 750 twres/images/back.png /twres/images/back.png" \
"add 750 twres/images/warningSign.png /twres/images/warningSign.png" \
"add 750 twres/images/c_battery_90.png /twres/images/c_battery_90.png" \
"add 750 twres/images/c_usersRadioOff.png /twres/images/c_usersRadioOff.png" \
"add 750 twres/images/editFile.png /twres/images/editFile.png" \
"add 750 twres/images/c_usersRadioOn.png /twres/images/c_usersRadioOn.png" \
"add 750 twres/images/c_dashboard_backup.png /twres/images/c_dashboard_backup.png" \
"add 750 twres/images/c_usb_disabled.png /twres/images/c_usb_disabled.png" \
"add 750 twres/images/actionZipOperation.png /twres/images/actionZipOperation.png" \
"add 750 twres/images/listcolorDarkViolate.png /twres/images/listcolorDarkViolate.png" \
"add 750 twres/images/c_backup_encryption.png /twres/images/c_backup_encryption.png" \
"add 750 twres/images/c_rounded_3.png /twres/images/c_rounded_3.png" \
"add 750 twres/images/folderUp.png /twres/images/folderUp.png" \
"add 750 twres/images/colorRed.png /twres/images/colorRed.png" \
"add 750 twres/images/c_battery_bar_040.png /twres/images/c_battery_bar_040.png" \
"add 750 twres/images/listcolorDeepBlue.png /twres/images/listcolorDeepBlue.png" \
"add 750 twres/images/listcolorOrange.png /twres/images/listcolorOrange.png" \
"add 750 twres/images/listcolorGreen.png /twres/images/listcolorGreen.png" \
"add 750 twres/images/colorDarkGreen.png /twres/images/colorDarkGreen.png" \
"add 750 twres/images/colorBrown.png /twres/images/colorBrown.png" \
"add 750 twres/images/c_dashboard_wipe.png /twres/images/c_dashboard_wipe.png" \
"add 750 twres/images/c_reload.png /twres/images/c_reload.png" \
"add 750 twres/images/c_usb.png /twres/images/c_usb.png" \
"add 750 twres/images/c_mtp_enabled.png /twres/images/c_mtp_enabled.png" \
"add 750 twres/images/actionArchive.png /twres/images/actionArchive.png" \
"add 750 twres/images/c_power_off.png /twres/images/c_power_off.png" \
"add 750 twres/images/actionApplyTheme.png /twres/images/actionApplyTheme.png" \
"add 750 twres/images/globeIco.png /twres/images/globeIco.png" \
"add 750 twres/images/magiskModule.png /twres/images/magiskModule.png" \
"add 750 twres/images/generalSettingsDisabled.png /twres/images/generalSettingsDisabled.png" \
"add 750 twres/images/permButton.png /twres/images/permButton.png" \
"add 750 twres/images/fileMangerSettings.png /twres/images/fileMangerSettings.png" \
"add 750 twres/images/c_reboot_to_system.png /twres/images/c_reboot_to_system.png" \
"add 750 twres/images/controlLock.png /twres/images/controlLock.png" \
"add 750 twres/images/actionRebootRecovery.png /twres/images/actionRebootRecovery.png" \
"add 750 twres/images/c_battery_bar_025.png /twres/images/c_battery_bar_025.png" \
"add 750 twres/images/deviceIco.png /twres/images/deviceIco.png" \
"add 750 twres/images/fileImg2.png /twres/images/fileImg2.png" \
"add 750 twres/images/folderUnselected.png /twres/images/folderUnselected.png" \
"add 750 twres/images/c_epicxsort.png /twres/images/c_epicxsort.png" \
"add 750 twres/images/c_mod.png /twres/images/c_mod.png" \
"add 750 twres/images/kb_arrow_left.png /twres/images/kb_arrow_left.png" \
"add 750 twres/images/c_battery_bar_050.png /twres/images/c_battery_bar_050.png" \
"add 750 twres/images/c_battery_bar_020.png /twres/images/c_battery_bar_020.png" \
"add 750 twres/images/actionRebootSystem.png /twres/images/actionRebootSystem.png" \
"add 750 twres/images/c_battery_bar_075.png /twres/images/c_battery_bar_075.png" \
"add 750 twres/images/c_repair.png /twres/images/c_repair.png" \
"add 750 twres/images/c_flash.png /twres/images/c_flash.png" \
"add 750 twres/images/c_edl_mode.png /twres/images/c_edl_mode.png" \
"add 750 twres/images/c_reboot.png /twres/images/c_reboot.png" \
"add 750 twres/images/deviceSettingsDisabled.png /twres/images/deviceSettingsDisabled.png" \
"add 750 twres/images/generalSettings.png /twres/images/generalSettings.png" \
"add 750 twres/images/fileLocExternal.png /twres/images/fileLocExternal.png" \
"add 750 twres/images/dashboardBackground.png /twres/images/dashboardBackground.png" \
"add 750 twres/images/kb_arrow_right.png /twres/images/kb_arrow_right.png" \
"add 750 twres/images/listcolorDark.png /twres/images/listcolorDark.png" \
"add 750 twres/images/folderSelected.png /twres/images/folderSelected.png" \
"add 750 twres/images/enter.png /twres/images/enter.png" \
"add 750 twres/images/colorPurple.png /twres/images/colorPurple.png" \
"add 750 twres/images/shrpSettingsDisabled.png /twres/images/shrpSettingsDisabled.png" \
"add 750 twres/images/file.png /twres/images/file.png" \
"add 750 twres/images/fileLocInternal.png /twres/images/fileLocInternal.png" \
"add 750 twres/images/c_battery_bar_030.png /twres/images/c_battery_bar_030.png" \
"add 750 twres/images/colorDeepBlue.png /twres/images/colorDeepBlue.png" \
"add 750 twres/images/colorOrange.png /twres/images/colorOrange.png" \
"add 750 twres/images/listcolorCyan.png /twres/images/listcolorCyan.png" \
"add 750 twres/images/controlFlashOn.png /twres/images/controlFlashOn.png" \
"add 750 twres/images/c_storage.png /twres/images/c_storage.png" \
"add 750 twres/images/c_rounded_2.png /twres/images/c_rounded_2.png" \
"add 750 twres/images/c_battery_bar_090.png /twres/images/c_battery_bar_090.png" \
"add 750 twres/images/toggleOff.png /twres/images/toggleOff.png" \
"add 750 twres/images/c_lock_pass.png /twres/images/c_lock_pass.png" \
"add 750 twres/images/search.png /twres/images/search.png" \
"add 750 twres/images/colorBlack.png /twres/images/colorBlack.png" \
"add 750 twres/images/openSideBar.png /twres/images/openSideBar.png" \
"add 750 twres/images/c_battery_low.png /twres/images/c_battery_low.png" \
"add 750 twres/images/c_battery_bar_035.png /twres/images/c_battery_bar_035.png" \
"add 750 twres/images/c_sd_part.png /twres/images/c_sd_part.png" \
"add 750 twres/images/c_on_tap_unlock_pressed.png /twres/images/c_on_tap_unlock_pressed.png" \
"add 750 twres/images/bt.png /twres/images/bt.png" \
"add 750 twres/images/c_refresh.png /twres/images/c_refresh.png" \
"add 750 twres/images/actionRename.png /twres/images/actionRename.png" \
"add 750 twres/images/installSign.png /twres/images/installSign.png" \
"add 750 twres/images/c_rounded_1.png /twres/images/c_rounded_1.png" \
"add 750 twres/images/colorIndigo.png /twres/images/colorIndigo.png" \
"add 750 twres/images/actionOption.png /twres/images/actionOption.png" \
"add 750 twres/images/colorTeal.png /twres/images/colorTeal.png" \
"add 750 twres/images/c_dash_text_box.png /twres/images/c_dash_text_box.png" \
"add 750 twres/images/c_format_data.png /twres/images/c_format_data.png" \
"add 750 twres/images/colorWhite.png /twres/images/colorWhite.png" \
"add 750 twres/images/c_dashboard_magisk.png /twres/images/c_dashboard_magisk.png" \
"add 750 twres/images/checkbox_true.png /twres/images/checkbox_true.png" \
"add 750 twres/images/colorDark.png /twres/images/colorDark.png" \
"add 750 twres/images/dashboardList.png /twres/images/dashboardList.png" \
"add 750 twres/images/editPermissions.png /twres/images/editPermissions.png" \
"add 750 twres/images/c_dashboard_filemanager.png /twres/images/c_dashboard_filemanager.png" \
"add 750 twres/images/actionCut.png /twres/images/actionCut.png" \
"add 750 twres/images/c_shadow.png /twres/images/c_shadow.png" \
"add 750 twres/images/kb_arrow_up.png /twres/images/kb_arrow_up.png" \
"add 750 twres/images/c_cancel.png /twres/images/c_cancel.png" \
"add 750 twres/images/listcolorBlue.png /twres/images/listcolorBlue.png" \
"add 750 twres/images/c_battery_bar_100.png /twres/images/c_battery_bar_100.png" \
"add 750 twres/images/c_selinux.png /twres/images/c_selinux.png" \
"add 750 twres/images/batteryList.png /twres/images/batteryList.png" \
"add 750 twres/images/fileLocRoot.png /twres/images/fileLocRoot.png" \
"add 750 twres/images/actionCreateFolder.png /twres/images/actionCreateFolder.png" \
"add 750 twres/images/c_battery_50.png /twres/images/c_battery_50.png" \
"add 750 twres/images/c_dashboard_restore.png /twres/images/c_dashboard_restore.png" \
"add 750 twres/images/listcolorTeal.png /twres/images/listcolorTeal.png" \
"add 750 twres/images/c_flashlight_off.png /twres/images/c_flashlight_off.png" \
"add 750 twres/images/deviceSettings.png /twres/images/deviceSettings.png" \
"add 750 twres/images/actionCopyLog.png /twres/images/actionCopyLog.png" \
"add 750 twres/images/cursor.png /twres/images/cursor.png" \
"add 750 twres/images/home.png /twres/images/home.png" \
"add 750 twres/images/c_battery_bar_010.png /twres/images/c_battery_bar_010.png" \
"add 750 twres/images/actionSelectMultipleFile.png /twres/images/actionSelectMultipleFile.png" \
"add 750 twres/images/c_dashboard_terminal.png /twres/images/c_dashboard_terminal.png" \
"add 750 twres/images/c_reboot_to_bootloader.png /twres/images/c_reboot_to_bootloader.png" \
"add 750 twres/images/colorGreen.png /twres/images/colorGreen.png" \
"add 750 twres/images/uninstallSign.png /twres/images/uninstallSign.png" \
"add 750 twres/images/c_on_tap_unlock.png /twres/images/c_on_tap_unlock.png" \
"add 750 twres/images/backspace.png /twres/images/backspace.png" \
"add 750 twres/images/colorRpink.png /twres/images/colorRpink.png" \
"add 750 twres/images/c_battery_bar_080.png /twres/images/c_battery_bar_080.png" \
"add 750 twres/images/shift.png /twres/images/shift.png" \
"add 750 twres/images/shrpCredits.png /twres/images/shrpCredits.png" \
"add 750 twres/images/c_dashboard_lock.png /twres/images/c_dashboard_lock.png" \
"add 750 twres/images/betaBuild.png /twres/images/betaBuild.png" \
"add 750 twres/images/c_dashboard_about.png /twres/images/c_dashboard_about.png" \
"add 750 twres/images/c_battery_bar_055.png /twres/images/c_battery_bar_055.png" \
"add 750 twres/images/space.png /twres/images/space.png" \
"add 750 twres/images/c_tab_backup_bg.png /twres/images/c_tab_backup_bg.png" \
"add 750 twres/images/colorYellow.png /twres/images/colorYellow.png" \
"add 750 twres/images/c_battery_60.png /twres/images/c_battery_60.png" \
"add 750 twres/images/toggleOn.png /twres/images/toggleOn.png" \
"add 750 twres/images/fileSelected.png /twres/images/fileSelected.png" \
"add 750 twres/images/timeSettings.png /twres/images/timeSettings.png" \
"add 750 twres/images/actionUnselectMultipleFile.png /twres/images/actionUnselectMultipleFile.png" \
"add 750 twres/images/c_flashlight_on.png /twres/images/c_flashlight_on.png" \
"add 750 twres/images/fileArchive.png /twres/images/fileArchive.png" \
"add 750 twres/images/actionDelete.png /twres/images/actionDelete.png" \
"add 750 twres/images/listcolorYellow.png /twres/images/listcolorYellow.png" \
"add 750 twres/images/c_splash_bg.png /twres/images/c_splash_bg.png" \
"add 750 twres/images/fileLocOtg.png /twres/images/fileLocOtg.png" \
"add 750 twres/images/c_dashboard_addon.png /twres/images/c_dashboard_addon.png" \
"add 750 twres/images/fileLocSystem.png /twres/images/fileLocSystem.png" \
"add 750 twres/images/c_queue.png /twres/images/c_queue.png" \
"add 750 twres/images/c_battery_bar_045.png /twres/images/c_battery_bar_045.png" \
"add 750 twres/images/actionCopy.png /twres/images/actionCopy.png" \
"add 750 twres/images/listcolorPurple.png /twres/images/listcolorPurple.png" \
"add 750 twres/images/c_battery_30.png /twres/images/c_battery_30.png" \
"add 750 twres/images/c_restoreDefault.png /twres/images/c_restoreDefault.png" \
"add 750 twres/images/backup.png /twres/images/backup.png" \
"add 750 twres/images/timeSettingsDisabled.png /twres/images/timeSettingsDisabled.png" \
"add 750 twres/images/c_dateSort.png /twres/images/c_dateSort.png" \
"add 750 twres/images/handle.png /twres/images/handle.png" \
"add 750 twres/images/goodSign.png /twres/images/goodSign.png" \
"add 750 twres/images/c_line_t.png /twres/images/c_line_t.png" \
"add 750 twres/images/c_log.png /twres/images/c_log.png" \
"add 750 twres/images/colorEnabled.png /twres/images/colorEnabled.png" \
"add 750 twres/images/c_battery_bar_001.png /twres/images/c_battery_bar_001.png" \
"add 750 twres/images/listcolorRpink.png /twres/images/listcolorRpink.png" \
"add 750 twres/images/c_battery_80.png /twres/images/c_battery_80.png" \
"add 750 twres/images/fileUnselected.png /twres/images/fileUnselected.png" \
"add 750 twres/images/sliderDot.png /twres/images/sliderDot.png" \
"add 750 twres/images/c_line.png /twres/images/c_line.png" \
"add 750 twres/images/c_clear_input.png /twres/images/c_clear_input.png" \
"add 750 twres/images/c_reset_lock.png /twres/images/c_reset_lock.png" \
"add 750 twres/images/listcolorRed.png /twres/images/listcolorRed.png" \
"add 750 twres/images/c_circle4.png /twres/images/c_circle4.png" \
"add 750 twres/images/listcolorIndigo.png /twres/images/listcolorIndigo.png" \
"add 750 twres/images/c_dashboard_advanced.png /twres/images/c_dashboard_advanced.png" \
"add 750 twres/images/console.png /twres/images/console.png" \
"add 750 twres/images/radio_false.png /twres/images/radio_false.png" \
"add 750 twres/images/c_battery_bar_000.png /twres/images/c_battery_bar_000.png" \
"add 750 twres/images/c_delete.png /twres/images/c_delete.png" \
"add 750 twres/images/c_battery_bar_070.png /twres/images/c_battery_bar_070.png" \
"add 750 twres/images/c_reboot_to_recovery.png /twres/images/c_reboot_to_recovery.png" \
"add 750 twres/images/c_lock_patt.png /twres/images/c_lock_patt.png" \
"add 750 twres/images/c_advanced.png /twres/images/c_advanced.png" \
"add 750 twres/images/kb_arrow_down.png /twres/images/kb_arrow_down.png" \
"add 750 twres/images/c_ok.png /twres/images/c_ok.png" \
"add 750 twres/images/listcolorDarkPurple.png /twres/images/listcolorDarkPurple.png" \
"add 750 twres/images/c_dashboard_settings.png /twres/images/c_dashboard_settings.png" \
"add 750 twres/images/listcolorPink.png /twres/images/listcolorPink.png" \
"add 750 twres/images/c_rounded_4.png /twres/images/c_rounded_4.png" \
"add 750 twres/images/controlFlashOff.png /twres/images/controlFlashOff.png" \
"add 750 twres/images/radio_true.png /twres/images/radio_true.png" \
"add 750 twres/images/SKYHAWK.png /twres/images/SKYHAWK.png" \
"add 750 twres/images/c_logo.png /twres/images/c_logo.png" \
"add 750 twres/images/colorLred.png /twres/images/colorLred.png" \
"add 750 twres/images/listcolorBlack.png /twres/images/listcolorBlack.png" \
"add 750 twres/images/c_battery_full.png /twres/images/c_battery_full.png" \
"add 750 twres/images/checkbox_false.png /twres/images/checkbox_false.png" \
"add 750 twres/images/c_battery_bar_095.png /twres/images/c_battery_bar_095.png" \
"add 750 twres/images/colorDarkViolate.png /twres/images/colorDarkViolate.png" \
"add 750 twres/images/c_mtp_disabled.png /twres/images/c_mtp_disabled.png" \
"add 750 twres/images/c_dashboard_userFbe.png /twres/images/c_dashboard_userFbe.png" \
"add 750 twres/images/colorDarkBlue.png /twres/images/colorDarkBlue.png" \
"add 750 twres/images/listcolorDarkBlue.png /twres/images/listcolorDarkBlue.png" \
"add 750 twres/images/colorBlue.png /twres/images/colorBlue.png" \
"add 750 twres/images/c_dashboard_lang.png /twres/images/c_dashboard_lang.png" \
"add 750 twres/images/colorDarkPurple.png /twres/images/colorDarkPurple.png" \
"add 750 twres/dynamic/themeData.xml /twres/dynamic/themeData.xml" \
"add 750 twres/slts /twres/slts"
