#!/sbin/sh
# SHRP Magisk Manager extra file
# Giovix92

# Kanged from mm
exxit() {
  set +euo pipefail
  cd /
  umount -l /_magisk
  rmdir /_magisk
} 2>/dev/null

if [ -d "/tmp/_magisk/.core" ]; then
	mv /tmp/.core /_magisk/
fi
if [ -d "/tmp/_magisk/lost+found/" ]; then
	mv /tmp/lost+found /_magisk/
fi

exxit
